name: deploy runner  # name of the workflow
on: [workflow_dispatch]  # event

jobs:                    # jobs/stages
 deploy-runner:          # job name, workflow can run multiple jobs parallelly
  runs-on: ubuntu-latest # agent node

  steps:                 # tasks inside the job
  - name: git clone
    uses: actions/checkout@v7

  - name: list files
    run: ls -l
    